### ISSUE TITLE
Typescript classes not defined?

### ISSUE THREAD

**Issue by vrecluse** [Sanjo/meteor-jasmine#224]
eg. class in my client code:
```
    class A {
    }
    this.A = A;
```
I can use A in other files, but when I use it in integrated tests, jasmine complains not defined.

**Comment by vrecluse** [comment]
Resolved, classes can not be used except in steps or befores.

**Comment by Sanjo** [comment]
I think that has something to do with the loading order. I've created a new issue for this: https://github.com/Sanjo/meteor-jasmine/issues/225. I fixed that case in server integration mode some time ago. But probably it still exists in client integration mode.
